name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./DOE522Project_SA  # Specify the working directory

    - name: Build
      run: npm run build
      working-directory: ./DOE522Project_SA  # Specify the working directory

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./DOE522Project_SA

    - name: Run unit tests
      run: npm test
      working-directory: ./DOE522Project_SA

    - name: Code quality checks
      run: echo "Add code quality check commands"

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./DOE522Project_SA

    - name: Deploy to staging environment
      run: echo "Add deployment commands"
